inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'app/views/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'bin/**'
