inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

AllCops:
  DisabledByDefault: true
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'
    - 'app/views/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'bin/**'
